//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.02 at 06:34:50 PM COT 
//


package domain.disponibilidad.entity;

import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Unmarshaller;
import javax.xml.bind.annotation.*;
import java.io.File;


/**
 * <p>Java class for datos complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="datos">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="empresa" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="servicio" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="disponibilidad" type="{}disponibilidad"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "datos", propOrder = {
    "empresa",
    "servicio",
    "disponibilidad"
})
@XmlRootElement(name="datos")
public class Datos {

    @XmlElement(required = true)
    protected String empresa;
    @XmlElement(required = true)
    protected String servicio;
    @XmlElement(required = true)
    protected Disponibilidad disponibilidad;

    /**
     * Gets the value of the empresa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmpresa() {
        return empresa;
    }

    /**
     * Sets the value of the empresa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmpresa(String value) {
        this.empresa = value;
    }

    /**
     * Gets the value of the servicio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServicio() {
        return servicio;
    }

    /**
     * Sets the value of the servicio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServicio(String value) {
        this.servicio = value;
    }

    /**
     * Gets the value of the disponibilidad property.
     * 
     * @return
     *     possible object is
     *     {@link Disponibilidad }
     *     
     */
    public Disponibilidad getDisponibilidad() {
        return disponibilidad;
    }

    /**
     * Sets the value of the disponibilidad property.
     * 
     * @param value
     *     allowed object is
     *     {@link Disponibilidad }
     *     
     */
    public void setDisponibilidad(Disponibilidad value) {
        this.disponibilidad = value;
    }

    public static String FILE_PROVEEDOR = "c:/FinalPatrones/proveedor.xml";
    public static Datos datos;
    public static void cargarDatos() {
        try {

            File file = new File(FILE_PROVEEDOR);
            JAXBContext jaxbContext = JAXBContext.newInstance(Datos.class);

            Unmarshaller jaxbUnmarshaller = jaxbContext.createUnmarshaller();
            datos = (Datos) jaxbUnmarshaller.unmarshal(file);
            System.out.println(datos);

        } catch (JAXBException e) {
            e.printStackTrace();
        }
    }
}
